name: easy_transition
description: flutter package for animated navigation and transition in both scal and fade transition, supporting all curves in sacle transition
version: 0.0.2
homepage: https://github.com/MOUKZ/easy_transition

environment:
  sdk: ">=2.12.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  flutter:
    sdk: flutter

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:


  